database:
  name: //app/db.sqlite3
  schema: sqlite+aiosqlite
host: 0.0.0.0
port: 8080
s3:
  bucket_name: med-calendar-assist
secret_key: DZwc6vjOYFjmouBDrxCWPGpgA815R1DY68QStPf1bB8=
JWT_ALGORITHM: HS256
JWT_EXP_DELTA_SECONDS: 3600
